/**
 * ESLint was a dependency of this project for a long time with no configuration
 * file and no script, so nothing ever ran it. Turning it on reported eight real
 * errors, five of them React hooks rules that no amount of typechecking finds:
 * `setState` in an effect body, and a ref written during render.
 *
 * The three blocks below are, in order: Next's own rules, the extra ratchets
 * this project wants, and the exemptions those ratchets need.
 */

import nextPlugin from "eslint-config-next";
import coreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";

/**
 * `eslint-config-next` ships flat config, but the three entry points disagree on
 * whether they export an array or a module with a default. Normalise rather than
 * guess, so a patch release cannot break the lint run.
 */
const flat = (mod) =>
  Array.isArray(mod)
    ? mod
    : Array.isArray(mod?.default)
      ? mod.default
      : [mod?.default ?? mod];

export default [
  {
    ignores: [
      ".next/**",
      ".next-test/**",
      "node_modules/**",
      "drizzle/**",
      "public/**",
      // Generated by `npm run test:coverage`. Linting a report about the code
      // is not linting the code.
      "coverage/**",
      "next-env.d.ts",
    ],
  },

  ...flat(nextPlugin),
  ...flat(coreWebVitals),
  ...flat(nextTypescript),

  {
    name: "cooking-app/ratchets",
    files: ["**/*.ts", "**/*.tsx"],
    rules: {
      // The codebase has none of these today. The rules keep it that way, which
      // is cheaper than removing the first one that lands.
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-non-null-assertion": "error",

      // `import type` where the import is only a type. `verbatimModuleSyntax` is
      // on, so the distinction is now load-bearing rather than cosmetic.
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { prefer: "type-imports", fixStyle: "inline-type-imports" },
      ],

      // An unused argument is usually a signature that outgrew its
      // implementation. Prefixing with `_` is the way to say it is deliberate.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],

      eqeqeq: ["error", "always", { null: "ignore" }],
      "no-console": ["error", { allow: ["error", "warn"] }],
      "prefer-const": "error",
      "object-shorthand": ["error", "properties"],
    },
  },

  {
    // Rule 3: one service layer behind both entry points. A component, a page or
    // a server action that reaches for the database directly is a business rule
    // that exists in only one of the two entry points, which is the thing the
    // rule exists to prevent. Nothing catches it at runtime, because the query
    // works.
    name: "cooking-app/service-layer",
    files: ["src/app/**", "src/components/**", "src/mcp/**"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@/db", "@/db/*", "**/db/schema", "**/db/schema/*"],
              message:
                "Query through a service in src/services. The web UI and the " +
                "MCP endpoint must share one service layer, so a rule cannot " +
                "exist in only one of them (CLAUDE.md rule 3).",
            },
          ],
        },
      ],
    },
  },

  {
    // Every environment variable is resolved in src/lib/config.ts, so a
    // development default cannot silently apply in production. That file is the
    // one place allowed to read the environment.
    name: "cooking-app/env-through-config",
    files: ["src/**/*.ts", "src/**/*.tsx"],
    ignores: ["src/lib/config.ts"],
    rules: {
      "no-restricted-properties": [
        "error",
        {
          object: "process",
          property: "env",
          message:
            'Read configuration through src/lib/config.ts. A `?? "localhost"` ' +
            "fallback written at the point of use applies in production too, " +
            "which is how a deployed instance ends up handing agents dead links.",
        },
      ],
    },
  },

  {
    // `NODE_ENV` is Next's own switch and is inlined by the bundler, so it is
    // read where it is needed, including in client components where config.ts
    // (which touches node:fs) cannot go.
    name: "cooking-app/node-env-exempt",
    files: ["src/components/service-worker.tsx", "src/lib/access.ts"],
    rules: { "no-restricted-properties": "off" },
  },

  {
    // Two files reach the database without a service, and both are
    // infrastructure rather than a business rule:
    //
    // - The health endpoint's whole job is to prove the connection works. Going
    //   through a service would report on the service instead.
    // - `tool-runner` is the layer that builds the `ServiceContext` every MCP
    //   tool then uses, and it writes the agent audit log. It sits beside the
    //   services rather than above them.
    name: "cooking-app/infrastructure-db-access",
    files: ["src/app/api/health/route.ts", "src/mcp/tool-runner.ts"],
    rules: { "no-restricted-imports": "off" },
  },

  {
    // Tests and scripts are the two places that set up an environment rather
    // than consume one, and a test reaches the database directly on purpose:
    // tests/rls.test.ts exists to prove tenancy at the connection level.
    name: "cooking-app/tests-and-scripts",
    files: ["tests/**", "scripts/**", "*.config.ts", "*.config.mjs"],
    rules: {
      "no-restricted-imports": "off",
      "no-restricted-properties": "off",
      "no-console": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
      "import/no-anonymous-default-export": "off",
    },
  },
];
